### ISSUE TITLE
Use of undeclared identifier 'ShortcutsModule'

### ISSUE THREAD

**Issue by adrianso** [Gustash/react-native-siri-shortcut#64] opened 2020-12-03 09:21 UTC
First of all, many thanks to Gustash creating this great library. It has been working great for me in the development environment, but I need help getting the code to compile in Release mode. Like the other user for Issue #58, I am getting the dreaded `Use of undeclared identifier 'ShortcutsModule'` error.

I have created the simplest clean repo to reproduce the problem.
To reproduce, do the following:
```
> git clone https://github.com/adrianso/react-native-siri-shortcut-reproduction.git
> yarn
> cd ios && pod install
```

The following compiles with no problems
```
> yarn ios
```

The next command will reproduce the compilation error `Use of undeclared identifier 'ShortcutsModule'`
```
> yarn ios --configuration="Release"
```

Some background
- React Native 0.63.4
- No other native modules apart from `react-native-siri-shortcut`
- Did not (cannot) use framework

**Comment by Gustash** [comment] 2020-12-12 11:25
Duplicate of #58

**Closed** 2020-12-12 11:25 UTC
