### ISSUE TITLE
Can we get SIRI intents in this library ? 

### ISSUE THREAD

**Issue by coolvasanth** [Gustash/react-native-siri-shortcut#121] opened 2023-01-09 10:48 UTC
Requirement: 
Basically I want to build an application that will take certain parameters from user over voice and processes it and returns the result. 
Simple ex: Todo App, 
User will invoke SIRI by saying 
1. "Hey SIRI create a todo for me "
2. Siri opens up and asks "What is the todo that I need to add " ?
3. User says a sample note "reminder to exercise"
4. Siri passes that information to app and asks another information "When the todo needs to be completed' ?
5. User says some date.
6. Post that the the details are processed and todo is stored and success message shown to user via SIRI. 

Can you please confirm such functionality can be achieved with this library ?

**Comment by Gustash** [comment] 2023-01-09 12:42
Duplicate of #3.

**Closed** 2023-01-09 12:42 UTC

**Comment by coolvasanth** [comment] 2023-01-10 08:44
Hi @Gustash thanks for adding your comment. This is quite critical for our project I know the library doesn't support the requirement, but can you give a lead on how to achieve it ? I can work on that and later add it to this library too !!

**Comment by Gustash** [comment] 2023-01-10 09:24
> Hi @Gustash thanks for adding your comment. This is quite critical for our project I know the library doesn't support the requirement, but can you give a lead on how to achieve it ? I can work on that and later add it to this library too !!

The library doesn't support it because it's impossible to write a generic implementation of Siri Intents without native, compiled code. 

You can look at the Apple Siri Intent documentation, which is what you'd want to implement. You'll also figure out why an implementation of it in a JavaScript library is unpractical

**Comment by coolvasanth** [comment] 2023-01-10 09:34
Gustash, one last comment. In fact I have tried implementing the native Siri intents on React Native project and I'm able to invoke SIRI and read parameters from SIRI voice input. The part that I'm struggling is passing that information to react native where the information needs to be processed and result needs to be sent to native layer, so that we can show success message there. 
Please let know if you have any idea on achieving this !!

**Comment by Gustash** [comment] 2023-01-10 10:54
> Gustash, one last comment. In fact I have tried implementing the native Siri intents on React Native project and I'm able to invoke SIRI and read parameters from SIRI voice input. The part that I'm struggling is passing that information to react native where the information needs to be processed and result needs to be sent to native layer, so that we can show success message there. 
> 
> Please let know if you have any idea on achieving this !! 

You can't run the JavaScript Bridge on the Intent Handler, you'll need to write all the Intent logic natively.

**Comment by invifire** [comment] 2024-03-11 11:00
@coolvasanth can you share did you found out anyway to archive it?
