### ISSUE TITLE
RNSiriShortcuts/RNSiriShortcuts-Swift.h' file not found

### ISSUE THREAD

**Issue by bougarfaoui** [Gustash/react-native-siri-shortcut#34] opened 2020-02-06 17:57 UTC
Hi thanks for this Repo, I can't build my project it gives me ```RNSiriShortcuts/RNSiriShortcuts-Swift.h' file not found```.
I tried  also to link it manually but it gave me the same error.

i'm using react native ```0.61.5```.

**Comment by daveadapptor** [comment] 2020-02-18 02:03
Just tried this library and hit the same issue.  Upgraded our RN to 0.61.5 to use the automatic linking but hit that same error about the missing header.  Also having problems with Typescript as theres no types for this library?

**Comment by Gustash** [comment] 2020-02-18 07:22
Can I see your Profile? Also yes, this library doesn't have any typescript declarations. You can feel free to made a declarations file and send it in a PR if you have some time, it would be very much appreciated

**Comment by bougarfaoui** [comment] 2020-02-18 15:36
@Gustash here's my podfile, I tried also to add ```use_frameworks!```but the result is the same.

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'wix' do
  # Pods for wix
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSound', :path => '../node_modules/react-native-sound' 
  pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'
  pod 'RCTSystemSetting', :path => '../node_modules/react-native-system-setting'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'FBAudienceNetwork', '~> 5.6.0'
  pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'
  pod 'FBSDKCoreKit'

  pod 'RNRate', :path => '../node_modules/react-native-rate'
  pod 'Google-Mobile-Ads-SDK'
  pod 'react-native-admob', path: '../node_modules/react-native-admob'
  pod 'react-native-mopub-sdk', path: '../node_modules/react-native-mopub-sdk'
  # target 'wixTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  use_native_modules!
end

target 'wix-tvOS' do
  # Pods for wix-tvOS

  target 'wix-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end



post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
```

**Comment by jackychanfox** [comment] 2020-02-27 10:12
hi, @bougarfaoui 
Please manual link and
add following to the *Header Search Path* of RNSiriShortcuts.xcodeproj
$(SRCROOT)/../../../ios/Pods/Headers
$(SRCROOT)/../../../ios/Pods/Headers/Public 

This will help you to resolve your issue.

**Comment by Gustash** [comment] 2020-03-04 16:38
Any updates on this at all? I still haven't been given a reproducible example, so I'll be closing this if nothing comes up before the end of the month

**Comment by daveadapptor** [comment] 2020-03-05 00:43
Personally I gave up and. implemented what I needed myself.  You asked for a Podfile and one was provided above.  I simply did yarn add react-native-siri, pod install (with and without use_frameworks) and tried to use the library and got the error mentioned.

**Comment by Gustash** [comment] 2020-03-05 09:09
I tried a project with the pods provided in that Podfile and couldn't replicate the issue. Also, did you do `yarn add react-native-siri-shortcut`? From your comment it seems you installed the wrong package

**Comment by Gustash** [comment] 2020-03-05 17:35
@bougarfaoui is it possible for you to provide me with an example project where this issue is happening? this would make debugging this much easier

**Comment by high-performance-hery** [comment] 2020-03-20 16:43
@Gustash Getting this issue and I can't seem to be able to link manually. What would the steps be to do that? I'd like to not have to use `use_frameworks!` as it conflicts with other libs in my project

**Comment by Gustash** [comment] 2020-03-20 18:09
@high-performance-hery I read that CocoaPods changed some things recently surrounding static linking for Swift projects. You can try to build without use_frameworks! on CocoaPods 1.9.1, but I haven't tried it so I don't know if it works. 

If you're using RN 0.61+, packages can no longer be manually linked since they removed the React.xcproj, so you need to use CocoaPods if that's the case

**Comment by gavrichards** [comment] 2020-03-23 16:29
I'm finding this problem too.

> .../AppDelegate.m:17:9: 'RNSiriShortcuts/RNSiriShortcuts-Swift.h' file not found

I can't add `use_frameworks!` to my Podfile because if I do then I get this error when running `pod install`:
```
Analyzing dependencies
Downloading dependencies
[!] The 'Pods-*****' target has transitive dependencies that include statically linked binaries: (/*****/ios/Pods/google-cast-sdk-no-bluetooth/GoogleCastSDK-ios-4.4.6_static/GoogleCast.framework)
```

(redacted my local path and project name)

I've updated Cocoapods to see if this would help but it hasn't made any difference.

Any help would be appreciated.

**Comment by high-performance-hery** [comment] 2020-03-25 09:29
@Gustash Thanks for your reply! Just wondering, is anything preventing you from releasing the lib as not a framework? Just forked it to see if I can remove that constraint

**Comment by Gustash** [comment] 2020-03-25 09:35
This was the main reason:

> With CocoaPods 1.5.0, developers are no longer restricted into specifying use_frameworks! in their Podfile in order to install pods that use Swift. Interop with Objective-C should just work. However, if your Swift pod depends on an Objective-C, pod you will need to enable "modular headers" (see below) for that Objective-C pod.

CocoaPods 1.9.1 introduces something new I haven't tried:

> Now that Swift supports static linking, CocoaPods has expanded this DSL to allow specifying the type of linkage preferred.

`use_frameworks! :linkage => :static`

Can anyone here try this on their project to see if this fixes the issue for them?

**Comment by Gustash** [comment] 2020-03-25 09:36
`modular_headers` for the React pod doesn't work btw, or at least it used to not like it very much

**Comment by Gustash** [comment] 2020-03-25 16:04
Any updates @high-performance-hery?

**Comment by high-performance-hery** [comment] 2020-03-25 16:06
@Gustash I've tried `use_frameworks! :linkage => :static` and it didn't build. Wrapping up other stuffs but I'll look again just a bit later, thanks!

**Comment by high-performance-hery** [comment] 2020-03-27 13:08
@Gustash Sadly I haven't been able to find a solution that enables both static libs and frameworks on 0.61.5. I've tried to set the static flag in the pre-install Flipper function, but it created other build issues.

However, by removing Flipper, which was our only static libs (AppCenter just fixed it in their latest release), it now builds properly. So I think that's going to be our short-term solution until there's a better CocoaPods/Swift/RN integration.

**Comment by Gustash** [comment] 2020-03-27 13:08
I think I just figured out something huge that'll make this package work as a static library. Meaning, no `use_frameworks!` necessary.

I'm making a new branch with these changes and releasing a new test version on NPM.

**Comment by Gustash** [comment] 2020-03-27 13:09
@high-performance-hery that's great! do you happen to have access to your project before the build was working though? I'd like you to confirm if this will fix the issue for other people

**Comment by high-performance-hery** [comment] 2020-03-27 13:09
Oh jinx good timing! Brilliant, I'll keep an eye out!

**Comment by Gustash** [comment] 2020-03-27 13:09
The timing on this was something else haha

**Comment by high-performance-hery** [comment] 2020-03-27 13:10
Haha! Yes I've got it on a separate branch as well, I can test your solution 👍

**Comment by Gustash** [comment] 2020-03-27 13:13
That's great! I'll let you know when and what version you can install to test this

**Comment by Gustash** [comment] 2020-03-27 13:34
@high-performance-hery can you install version `1.7.0-alpha.0`?

For this to work you need an empty swift file and a bridging header, if you don't have them already. To do this just right-click on your project name on Xcode, select New File, choose Swift file and put it anywhere (you can name it whatever you want). When it asks you if you want to create a Bridging Header, say yes.

Then, in your AppDelegate.m, change `#import <RNSiriShortcuts/RNSiriShortcuts-Swift.h>` with `@import RNSiriShortcuts;`

Obviously, remove `use_frameworks!` from your Podfile, and that should be it. Hopefully it'll build and the package will work just fine.

Tag me when you've tried this out please!

**Comment by high-performance-hery** [comment] 2020-03-27 19:29
Seems to work, I can keep Flipper now, nice work! :)

**Comment by Gustash** [comment] 2020-03-27 19:48
Awesome! I'll make a proper release and add more documentation on the README for this. Probably tomorrow

**Comment by Gustash** [comment] 2020-03-28 00:35
I'm glad to say that v1.7.0 enables installing this package as a static library. That means, no `use_frameworks!` necessary if you're willing to press a few more buttons on Xcode.

I've updated the README with some new instructions for doing this, as well as a small change in the `AppDelegate.m`.

If something is still not working, or the instructions aren't very clear, please tag me here so I can reopen and take another look!

Closing.

**Closed by Gustash** 2020-03-28 00:35 UTC
