### ISSUE TITLE
clearAllShortcuts Method not working 

### ISSUE THREAD

**Issue by Farhankhaliid** [Gustash/react-native-siri-shortcut#53] opened 2020-08-31 21:42 UTC
async clearShortcuts() {
    clearAllShortcuts()
      .then(res => {
        console.log("deleted", res);
      })
      .catch(e => {
        console.log("Cant clear on <iOS 12", e);
      });
  }
but its not woking for me plz help .

**Comment by Gustash** [comment] 2020-09-10 10:11
What exactly isn't working? What are you seeing and what are you expecting to happen?

**Comment by rich-smith** [comment] 2020-10-07 18:26
I'm experiencing the same behaviour. 

Expectation:
- After creating and saving a shortcut, I tried to delete the shortcut using both the "clearAllShortcuts" and "clearShortcutsWithIdentifiers" methods respectively. 

Behaviour:
- After executing the above, my shortcut remains intact. (Confirmed by running "getShortcuts").

Environment:
- React Native 0.63.2
- react-native-siri-shortcut 1.9.2
- running on iPhone X

Additional info:
- I was unable to successfully run "pod install" while including  "use_frameworks!" in the Podfile and therefore commented it out. (Everything other than the two methods above are working as intended). 

Perhaps I'm misunderstanding the intended behaviour of these methods?

**Comment by Gustash** [comment] 2020-10-11 11:41
I'm inclined to think that you can't actually delete recorded shortcuts. Can you check if those shortcuts show up on the Shortcuts app, and if you see the same behaviour after manually deleting the recorded shortcut?

**Comment by rich-smith** [comment] 2020-10-11 12:17
If I manually delete the shortcut, then it is no longer listed when running "getShortcuts()". So perhaps Apple doesn't allow shortcuts to be programmatically deleted?

**Comment by Gustash** [comment] 2020-10-11 18:03
It appears so. The documentation isn't clear about this, but what I suspect is that you can't programatically remove a shortcut that a user has added to their Siri.

Since I haven't gotten a reply from @Farhankhaliid, I'm closing this issue. If the problem lies elsewhere, please re-open this issue.

**Closed by Gustash** 2020-10-11 18:03 UTC
